site_name: CiscoLive EMEA 2023 --- LABDCN-2542
site_description: ACI Anywhere using Cisco Cloud Network Controller (formerly Cloud APIC) with Practice Use-cases
site_author: Marcin Duma & Karol Okraska

nav:
  - Home: index.md
  - Lab Access: LAB_access-RDP.md
  - Explore Nexus Dashboard: 
    - Dashboard overview: nd.md
    - Orchestrator overview: ndo.md
    - Sites connectivity: infra-config.md
  - ACI to Public Cloud Object mapping: object-map.md
  - Tenant configuration:
    - NDO Tenant configuration: ndo-tenant.md
    - AWS Trust: aws-trust.md
  - Use-cases:
    - Use-case 01 - Stretched VRF: use-case1.md
    - Use-case 02 - Internet Gateway: use-case2.md
  - Appendixes:
    - Lab details:
      - POD-01: pod1x.md
      - POD-02: pod2x.md
      - POD-03: pod3x.md
      - POD-04: pod4x.md
      - POD-05: pod5x.md
      - POD-06: pod6x.md

    - Resources: resources.md
    - PRINT version: print_page/
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - tables

use_directory_urls: false
    
plugins:
  - search
  - print-site:
      add_cover_page: true
      cover_page_template: "docs/assets/templates/custom_cover_page.tpl"
      add_print_site_banner: true
      print_site_banner_template: "docs/assets/templates/custom_banner.tpl"
      exclude:
        - guacamole.md
        - resources.md
        - URL-restAPI.md
  - glightbox:
      touchNavigation: true
      loop: false
      effect: fade
      slide_effect: fade
      width: 80%
      height: auto
      zoomable: false
      draggable: true
      skip_classes:
      - custom-skip-class-name
      auto_caption: false
      caption_position: bottom